application: cloud-broker
version: 1
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: images

- url: /files
  static_dir: files

- url: /data
  static_dir: data

- url: /ampie
  static_dir: ampie

- url: /amstock
  static_dir: amstock

- url: /maintenance
  script: maintenance.py
  login: admin  

- url: /checkservers 
  script: checkservers.py
  login: admin

- url: /admin
  script: admin.py
  login: admin

- url: /admin/storeserver
  script: admin.py
  login: admin
  
- url: /admin/storeec2account
  script: admin.py
  login: admin
  
- url: /admin/deleteserver
  script: admin.py
  login: admin

- url: /admin/storeadminoptions
  script: admin.py
  login: admin

- url: /dashboard 
  script: dashboard.py

- url: .*
  script: frontpage.py

